### Extracting frame for the videos

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pip install tensorflow opencv-python moviepy scikit-learn


Note: you may need to restart the kernel to use updated packages.


In [3]:
import cv2
import os

In [4]:
## defining a function that extracts frames from the video fir furthur processes.

In [5]:
def extract_frames_from_video(video_path, frame_count=30):
    clip = VideoFileClip(video_path)
    frames = []
    duration = clip.duration
    for i in range(frame_count):
        frame = clip.get_frame(i * duration / frame_count)
        frame = cv2.resize(frame, (128, 128))
        frames.append(frame)
    return np.array(frames)

def load_dataset(directory, frame_count=30):
    data = []
    labels = []
    for filename in os.listdir(directory):
        if filename.endswith(".mp4"):
            video_path = os.path.join(directory, filename)
            frames = extract_frames_from_video(video_path, frame_count)
            data.append(frames)
            label = 1 if 'fake' in filename else 0  # Assuming filenames contain 'fake' for deep fakes
            labels.append(label)
    return np.array(data), np.array(labels)


In [6]:
train_dir = r"C:\Users\101ri\OneDrive\Desktop\deep fake detector\Notebook\train_sample_videos"
# test_dir = r"C:\Users\101ri\OneDrive\Desktop\deep fake detector\Notebook\test_videos"

In [7]:

# if os.path.exists(train_dir) and os.path.exists(test_dir):
#     print("Directories found.")
# else:
#     print("Directories not found.")

# # Example: Listing video files in the training directory
# train_videos = os.listdir(train_dir)
# print("Training videos:", train_videos)

# # Example: Listing video files in the testing directory
# test_videos = os.listdir(test_dir)
# print("Testing videos:", test_videos)


In [8]:
if os.path.exists(train_dir):
    print("directory found")
else:
    print("not found")

directory found


In [9]:
train_videos = os.listdir(train_dir)
print("training videos:", train_videos)

training videos: ['aagfhgtpmv.mp4', 'aapnvogymq.mp4', 'aassnaulhq.mp4', 'aayfryxljh.mp4', 'abarnvbtwb.mp4', 'abofeumbvv.mp4', 'abqwwspghj.mp4', 'acazlolrpz.mp4', 'acifjvzvpm.mp4', 'acqfdwsrhi.mp4', 'acxnxvbsxk.mp4', 'acxwigylke.mp4', 'aczrgyricp.mp4', 'adhsbajydo.mp4', 'adohdulfwb.mp4', 'adohikbdaz.mp4', 'adylbeequz.mp4', 'aelfnikyqj.mp4', 'aelzhcnwgf.mp4', 'aettqgevhz.mp4', 'aevrfsexku.mp4', 'afoovlsmtx.mp4', 'agdkmztvby.mp4', 'agqphdxmwt.mp4', 'agrmhtjdlk.mp4', 'ahbweevwpv.mp4', 'ahdbuwqxit.mp4', 'ahfazfbntc.mp4', 'ahjnxtiamx.mp4', 'ahqqqilsxt.mp4', 'aipfdnwpoo.mp4', 'ajiyrjfyzp.mp4', 'ajqslcypsw.mp4', 'ajwpjhrbcv.mp4', 'aklqzsddfl.mp4', 'aknbdpmgua.mp4', 'aknmpoonls.mp4', 'aktnlyqpah.mp4', 'akvmwkdyuv.mp4', 'akxoopqjqz.mp4', 'akzbnazxtz.mp4', 'aladcziidp.mp4', 'alaijyygdv.mp4', 'alninxcyhg.mp4', 'alrtntfxtd.mp4', 'altziddtxi.mp4', 'alvgwypubw.mp4', 'amaivqofda.mp4', 'amowujxmzc.mp4', 'andaxzscny.mp4', 'aneclqfpbt.mp4', 'anpuvshzoo.mp4', 'aomqqjipcp.mp4', 'aorjvbyxhw.mp4', 'apatcsqej

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
from moviepy.editor import VideoFileClip

In [12]:
## test-train split...

X, y = load_dataset(train_dir)


In [358]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [359]:
## normalizing the pixel value
X_train = X_train / 255.0
X_test = X_test / 255.0

MemoryError: Unable to allocate 7.03 GiB for an array with shape (640, 30, 128, 128, 3) and data type float64

### Model Development

In [15]:
import tensorflow as tf

In [16]:
!pip install tensorflow

In [17]:
!pip install keras

In [18]:
from tensorflow.keras import layers, models

In [19]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, TimeDistributed, LSTM, Dense, Flatten, Conv2D, MaxPooling2D


In [36]:
## processing
def create_cnn_lstm_model():
    model = Sequential([
        TimeDistributed(Conv2D(32, (3, 3), activation='relu'), input_shape=(30, 128, 128, 3)),
        TimeDistributed(MaxPooling2D((2, 2))),
        TimeDistributed(Flatten()),
        LSTM(128, return_sequences=False),
        Dense(128, activation='relu'),
        Dense(1, activation='sigmoid'),
        Dropout(0.5),  # 50% dropout
    Dense(10, activation='softmax')
    ])
    model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [38]:
from tensorflow.keras.layers import TimeDistributed

In [39]:
pip install moviepy

Note: you may need to restart the kernel to use updated packages.


In [40]:
def extract_frames_from_video(video_path, frame_count=30):
    clip = VideoFileClip(video_path)
    frames = []
    duration = clip.duration
    for i in range(frame_count):
        frame = clip.get_frame(i * duration / frame_count)
        frame = cv2.resize(frame, (128, 128))
        frames.append(frame)
    return np.array(frames)

In [41]:
print(extract_frames_from_video(r"test_videos/aayfryxljh.mp4", 30))

[[[[222 207 187]
   [229 210 194]
   [222 203 189]
   ...
   [ 57  49  57]
   [ 50  47  51]
   [ 62  41  67]]

  [[233 218 198]
   [229 210 194]
   [227 213 197]
   ...
   [ 57  46  53]
   [ 46  46  56]
   [ 45  35  36]]

  [[233 217 200]
   [225 215 193]
   [232 221 202]
   ...
   [ 50  45  33]
   [ 67  65  47]
   [115  91  84]]

  ...

  [[178 155 138]
   [176 153 140]
   [176 151 132]
   ...
   [ 72  38  36]
   [ 86  59  54]
   [ 79  48  40]]

  [[188 167 148]
   [171 150 135]
   [173 148 131]
   ...
   [ 92  55  54]
   [ 82  53  50]
   [ 73  56  48]]

  [[172 160 134]
   [171 150 139]
   [172 151 136]
   ...
   [ 57  33  27]
   [ 51  36  27]
   [ 48  40  27]]]


 [[[225 214 195]
   [224 207 197]
   [229 213 200]
   ...
   [ 63  51  51]
   [ 49  48  45]
   [ 47  42  37]]

  [[226 212 196]
   [227 211 196]
   [229 214 205]
   ...
   [ 61  47  52]
   [ 62  44  53]
   [ 54  41  49]]

  [[231 211 193]
   [228 218 194]
   [225 214 195]
   ...
   [ 67  58  71]
   [ 95  66  64]
   [113  87

In [42]:
## deining cnn models...

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
num_classes=10
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(512, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.summary()



Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_6 (Conv2D)                    │ (None, 126, 126, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_6 (MaxPooling2D)       │ (None, 63, 63, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 61, 61, 128)         │          36,992 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_7 (MaxPooling2D)       │ (None, 30, 30, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 28, 28, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_8 (MaxPooling2D)       │ (None, 14, 14, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_2 (Flatten)                  │ (None, 25088)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 512)                 │      12,845,568 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 10)                  │           5,130 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 13,036,170 (49.73 MB)

 Trainable params: 13,036,170 (49.73 MB)

 Non-trainable params: 0 (0.00 B)

In [1]:
def create_cnn_model():
    model = Sequential()
    model.add(Conv2D(32, (3, 3), activation='sigmoid', input_shape=(128, 128, 3)))
    model.add(MaxPooling2D((2, 2)))
    model.add(Conv2D(64, (3, 3), activation='relu'))
    model.add(MaxPooling2D((2, 2)))
    model.add(Conv2D(128, (3, 3), activation='sigmoid'))
    model.add(MaxPooling2D((2, 2)))
    model.add(Flatten())
    model.add(Dense(512, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))

## model compilation
    model.compile(optimizer=Adam(),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [2]:
model.summary()

NameError: name 'model' is not defined

In [68]:
## shape check
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (409, 128, 128, 3)
y_train shape: (409,)
X_test shape: (103, 128, 128, 3)
y_test shape: (103,)


In [69]:
def load_dataset(directory):
    # Assuming this function loads images and labels from the directory
    X = []  # Placeholder for images
    y = []  # Placeholder for labels
    
    # Your logic to load images and labels
    # Ensure that for every image loaded into X, a corresponding label is loaded into y
    
    return np.array(X), np.array(y)


In [70]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [71]:
from tensorflow.keras.optimizers import Adam

In [72]:
from keras.models import Sequential

In [73]:
X_train = X_train.reshape(-1, 128, 128, 3) 
X_test = X_test.reshape(-1, 128, 128, 3)

In [74]:
X_train = X_train[:min(len(X_train), len(y_train))]
y_train = y_train[:min(len(X_train), len(y_train))]


In [75]:
## model training
model = create_cnn_model()
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.7)

# model evalution
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Cnn Model Test Accuracy: {accuracy}')

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 421ms/step - accuracy: 0.5027 - loss: 1.5117 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 290ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 318ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 300ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 289ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 290ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 299ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 300ms/step - accura

In [76]:
print(X_train.shape)

(327, 128, 128, 3)


In [77]:
print(X_test.shape)

(82, 128, 128, 3)


In [78]:
print(X_train.dtype)
print(y_train.dtype)
print(X_train[:5])
print(y_train[:5])

float64
int32
[[[[0.44705882 0.41176471 0.30980392]
   [0.45882353 0.42352941 0.31764706]
   [0.45882353 0.41568627 0.34117647]
   ...
   [0.77254902 0.71372549 0.55686275]
   [0.74509804 0.69411765 0.56862745]
   [0.69411765 0.64705882 0.52941176]]

  [[0.43921569 0.4        0.31372549]
   [0.44313725 0.40392157 0.31764706]
   [0.43921569 0.40392157 0.29803922]
   ...
   [0.78431373 0.72941176 0.56078431]
   [0.74901961 0.69803922 0.57254902]
   [0.71372549 0.66666667 0.54901961]]

  [[0.44705882 0.4        0.29803922]
   [0.44705882 0.39607843 0.30588235]
   [0.43137255 0.39215686 0.29803922]
   ...
   [0.79607843 0.7372549  0.58823529]
   [0.75686275 0.71372549 0.57647059]
   [0.73333333 0.69019608 0.55686275]]

  ...

  [[0.45098039 0.39607843 0.29019608]
   [0.4627451  0.39215686 0.2745098 ]
   [0.47058824 0.39607843 0.29019608]
   ...
   [0.85882353 0.71372549 0.44313725]
   [0.81568627 0.69019608 0.41176471]
   [0.80392157 0.66666667 0.41176471]]

  [[0.44313725 0.38823529 0.290

In [79]:
X_train.shape[0] == len(y_train)

True

### LSTM and RNN

In [80]:
from tensorflow.keras.layers import SimpleRNN, LSTM

In [81]:
# Reshape the image data from (num_samples, height, width, channels) to (num_samples, timesteps, features)
# Here, timesteps = height and features = width * channels
X_train_rnn = X_train.reshape(X_train.shape[0], X_train.shape[1], -1)
X_test_rnn = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)

# Verify the new shapes
print(f'Reshaped X_train for RNN: {X_train_rnn.shape}')
print(f'Reshaped X_test for RNN: {X_test_rnn.shape}')

Reshaped X_train for RNN: (327, 128, 384)
Reshaped X_test for RNN: (82, 128, 384)


In [82]:
## define RNN model
def create_rnn_model(input_shape):
    model = Sequential()
    model.add(SimpleRNN(50, activation='relu', input_shape=input_shape))
    model.add(Dense(num_classes, activation='softmax'))
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [83]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_12 (Conv2D)                   │ (None, 126, 126, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_12 (MaxPooling2D)      │ (None, 63, 63, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_13 (Conv2D)                   │ (None, 61, 61, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_13 (MaxPooling2D)      │ (None, 30, 30, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_14 (Conv2D)                   │ (None, 28, 28, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_14 (MaxPooling2D)      │ (None, 14, 14, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_4 (Flatten)                  │ (None, 25088)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 512)                 │      12,845,568 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 10)                  │           5,130 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 38,831,840 (148.13 MB)

 Trainable params: 12,943,946 (49.38 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 25,887,894 (98.75 MB)

In [84]:
input_shape = (400, 128, 3)

In [85]:
## define the input shape for the RNN model
input_shape = (128, 128 * 3)  
    # timesteps = height, features = width * channels

## create and train the RNN model
rnn_model = create_rnn_model(input_shape)
history_rnn = rnn_model.fit(X_train_rnn, y_train, epochs=70, batch_size=2, validation_split=0.1)

## evaluate the RNN model
loss_rnn, accuracy_rnn = rnn_model.evaluate(X_test_rnn, y_test)
print(f'RNN Model Test Accuracy: {accuracy_rnn}')


Epoch 1/70
147/147 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.9812 - loss: 0.1934 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 2/70
147/147 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 3/70
147/147 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 4/70
147/147 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 5/70
147/147 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 6/70
147/147 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 7/70
147/147 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - accuracy: 1.0000 - loss: 0.0000e+00 - val_accuracy: 1.0000 - val_loss: 0.0000e+00
Epoch 8/70
147/147 ━━━━━━━━━━━━━━━━━━━━ 3s 11

In [116]:
from tensorflow.keras.layers import Dropout

In [117]:
num_class=20

In [139]:
def create_lstm_model(input_shape, num_class):
    model = Sequential()
    model.add(LSTM(50, activation='relu', input_shape=input_shape))
    model.add(Dense(128, activation='relu'))
   
  
    model.add(Dropout(0.5))
    model.add(Dense(num_classes, activation='softmax'))

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

In [140]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_12 (Conv2D)                   │ (None, 126, 126, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_12 (MaxPooling2D)      │ (None, 63, 63, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_13 (Conv2D)                   │ (None, 61, 61, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_13 (MaxPooling2D)      │ (None, 30, 30, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_14 (Conv2D)                   │ (None, 28, 28, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_14 (MaxPooling2D)      │ (None, 14, 14, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_4 (Flatten)                  │ (None, 25088)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 512)                 │      12,845,568 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 10)                  │           5,130 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 38,831,840 (148.13 MB)

 Trainable params: 12,943,946 (49.38 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 25,887,894 (98.75 MB)

In [141]:
import numpy as np

# Convert the image data to the format required by LSTM
# timesteps = height of the image, features = width * channels
X_train_lstm = X_train.reshape(X_train.shape[0], X_train.shape[1], -1)  # (num_samples, timesteps, features)
X_test_lstm = X_test.reshape(X_test.shape[0], X_test.shape[1], -1)    # (num_samples, timesteps, features)

# Verify the new shapes
print(f'Reshaped X_train for LSTM: {X_train_lstm.shape}')
print(f'Reshaped X_test for LSTM: {X_test_lstm.shape}')


Reshaped X_train for LSTM: (327, 128, 384)
Reshaped X_test for LSTM: (82, 128, 384)


In [142]:
# 261: Number of samples (or batches) in the training data.
# 128: Number of time steps (or sequences) in each sample.
# 384: Number of features (or dimensions) in each time step.

In [143]:
## define the input shape for the LSTM model
input_shape = (128, 128 * 3)  # timesteps = height, features = width * channels

## create and train the LSTM model
lstm_model = create_lstm_model(input_shape, num_class)
history_lstm = lstm_model.fit(X_train_lstm, y_train, epochs=20, batch_size=8, validation_split=0.2)

## evaluate the LSTM model
loss_lstm, accuracy_lstm = lstm_model.evaluate(X_test_lstm, y_test)
print(f'LSTM Model Test Accuracy: {accuracy_lstm}')


Epoch 1/20
33/33 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - accuracy: 0.2647 - loss: 20.2068 - val_accuracy: 1.0000 - val_loss: 0.9311
Epoch 2/20
33/33 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.9638 - loss: 0.8786 - val_accuracy: 0.7273 - val_loss: 418.3470
Epoch 3/20
33/33 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.9506 - loss: 2464.8572 - val_accuracy: 1.0000 - val_loss: 0.0433
Epoch 4/20
33/33 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.9986 - loss: 0.0931 - val_accuracy: 1.0000 - val_loss: 0.0194
Epoch 5/20
33/33 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.9983 - loss: 0.0501 - val_accuracy: 1.0000 - val_loss: 0.0143
Epoch 6/20
33/33 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - accuracy: 0.9987 - loss: 0.0397 - val_accuracy: 1.0000 - val_loss: 0.0104
Epoch 7/20
33/33 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 1.0000 - loss: 0.0266 - val_accuracy: 1.0000 - val_loss: 0.0080
Epoch 8/20
33/33 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 1.0000 - loss: 0.0172 - val_accuracy: 1.00

### Working together with lstm and cnn model

Current Size:

Your array size is 4030464 elements.
Target Shape:

The target shape you attempted is (2, 30, 128, 128, 3).
Calculating the Required Size for Target Shape:

The target shape would require 2 * 30 * 128 * 128 * 3 = 2949120 elements.

In [349]:
# Assuming X_train is your data with shape (num_samples, 128, 128, 3)
num_samples = X_train.shape[0]
num_sequences = num_samples // 30  # Number of sequences you can form

# Reshape data into sequences
X_train = X_train[:num_sequences * 30].reshape(num_sequences, 30, 128, 128, 3)


In [350]:
def create_cnn_lstm_model():
    model = Sequential([
        TimeDistributed(Conv2D(32, (3, 3), activation='relu'), input_shape=(30, 128, 128, 3)),
        TimeDistributed(MaxPooling2D((2, 2))),
        TimeDistributed(Flatten()),
        LSTM(64, return_sequences=False),
        
        Dense(64, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer
                  =Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [300]:
# Training CNN-LSTM
cnn_lstm_model = create_cnn_lstm_model()
history_cnn_lstm = cnn_lstm_model.fit(X_train, y_train, epochs=20, batch_size=8, validation_split=0.2)
loss_cnn_lstm, accuracy_cnn_lstm = cnn_lstm_model.evaluate(X_test, y_test)
print(f'CNN-LSTM Model Test Accuracy: {accuracy_cnn_lstm:.4f}')

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 25s 25s/step - accuracy: 0.0000e+00 - loss: 0.8078 - val_accuracy: 1.0000 - val_loss: 0.1410
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 23s 23s/step - accuracy: 1.0000 - loss: 0.1433 - val_accuracy: 1.0000 - val_loss: 0.1227
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 18s 18s/step - accuracy: 1.0000 - loss: 0.1231 - val_accuracy: 1.0000 - val_loss: 0.1065
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 19s 19s/step - accuracy: 1.0000 - loss: 0.1065 - val_accuracy: 1.0000 - val_loss: 0.0921
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 23s 23s/step - accuracy: 1.0000 - loss: 0.0920 - val_accuracy: 1.0000 - val_loss: 0.0795
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 19s 19s/step - accuracy: 1.0000 - loss: 0.0795 - val_accuracy: 1.0000 - val_loss: 0.0686
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 23s 23s/step - accuracy: 1.0000 - loss: 0.0688 - val_accuracy: 1.0000 - val_loss: 0.0594
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 28s 28s/step - accuracy: 1.0000 - loss: 0.0596 - val_accuracy: 1.0000 - val_loss: 0.0

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=float32)
  • training=False
  • mask=None

In [302]:
cnn_lstm_model.summary()

Model: "sequential_25"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ time_distributed_43                  │ (None, 30, 126, 126, 32)    │             896 │
│ (TimeDistributed)                    │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ time_distributed_44                  │ (None, 30, 63, 63, 32)      │               0 │
│ (TimeDistributed)                    │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ time_distributed_45                  │ (None, 30, 127008)          │               0 │
│ (TimeDistributed)                    │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_22 (LSTM)                       │ (None, 64)                  │      32,530,688 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_41 (Dense)                     │ (None, 64)                  │           4,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_42 (Dense)                     │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 97,607,429 (372.34 MB)

 Trainable params: 32,535,809 (124.11 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 65,071,620 (248.23 MB)

In [ ]:
from tensorflow.keras.layers import TimeDistributed

In [303]:
from tensorflow.keras.layers import Layer, Input
from tensorflow.keras import initializers, activations
import tensorflow.keras.backend as K

### Capsule Networks

In [309]:
import tensorflow as tf
from tensorflow.keras.layers import Layer, Conv2D, Dense, Flatten, Input
from tensorflow.keras.models import Model

class CapsuleLayer(Layer):
    def __init__(self, num_capsules, dim_capsules, **kwargs):
        super(CapsuleLayer, self).__init__(**kwargs)
        self.num_capsules = num_capsules
        self.dim_capsules = dim_capsules

    def build(self, input_shape):
        self.input_dim = input_shape[-1]
        self.W = self.add_weight(shape=(self.input_dim, self.num_capsules, self.dim_capsules),
                                 initializer='glorot_uniform', name='W')

    def call(self, inputs):
        inputs_tiled = tf.tile(inputs, [1, self.num_capsules, 1, 1])  # Tile before expanding
        inputs_expand = tf.expand_dims(inputs_tiled, 1)  # Expand after tiling
        inputs_expand = tf.matmul(inputs_expand, self.W)  # Capsule routing
        return self.squash(inputs_expand)

    def squash(self, inputs, axis=-1):
        norm = tf.sqrt(tf.reduce_sum(tf.square(inputs), axis=axis, keepdims=True))
        return (norm / (1 + norm)) * (inputs / norm)

def create_capsule_model(input_shape, num_classes):
    inputs = Input(shape=input_shape)
    x = Conv2D(256, (9, 9), activation='relu')(inputs)
    x = tf.keras.layers.Reshape(target_shape=(-1, 256))(x)
    x = CapsuleLayer(num_capsules=32, dim_capsules=8)(x)
    x = Flatten()(x)
    x = Dense(512, activation='relu')(x)
    outputs = Dense(num_classes, activation='softmax')(x)
    model = Model(inputs, outputs)
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Define the input shape and number of classes
input_shape = (128, 128, 3)
num_classes = 10

# Creating and training the Capsule Network model
capsule_model = create_capsule_model(input_shape, num_classes)
history_capsule = capsule_model.fit(X_train, y_train, epochs=20, batch_size=8, validation_split=0.2)

# Evaluate the Capsule Network model
loss_capsule, accuracy_capsule = capsule_model.evaluate(X_test, y_test)
print(f'Capsule Network Test Accuracy: {accuracy_capsule:.4f}')

ValueError: Exception encountered when calling CapsuleLayer.call().

Could not automatically infer the output shape / dtype of 'capsule_layer_4' (of type CapsuleLayer). Either the `CapsuleLayer.call()` method is incorrect, or you need to implement the `CapsuleLayer.compute_output_spec() / compute_output_shape()` method. Error encountered:

Shape must be rank 3 but is rank 4 for '{{node Tile}} = Tile[T=DT_FLOAT, Tmultiples=DT_INT32](Placeholder, Tile/multiples)' with input shapes: [?,14400,256], [4].

Arguments received by CapsuleLayer.call():
  • args=('<KerasTensor shape=(None, 14400, 256), dtype=float32, sparse=False, name=keras_tensor_428>',)
  • kwargs=<class 'inspect._empty'>

### GANs

In [310]:
from tensorflow.keras.layers import Dense, Reshape, LeakyReLU
from tensorflow.keras.models import Sequential

In [ ]:
## model generator

In [311]:
def build_generator():
    model = Sequential()
    model.add(Dense(128, input_dim=100))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(256))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(512))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(28 * 28 * 1, activation='tanh'))
    model.add(Reshape((28, 28, 1)))
    return model

## discriminator Model
def build_discriminator():
    model = Sequential()
    model.add(Dense(512, input_shape=(28, 28, 1)))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(256))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(1, activation='sigmoid'))
    return model

## GAN model
def build_gan(generator, discriminator):
    discriminator.trainable = False
    model = Sequential([generator, discriminator])
    return model

## initiate model
generator = build_generator()
discriminator = build_discriminator()
gan = build_gan(generator, discriminator)

In [312]:
model

<Sequential name=sequential_5, built=False>

In [313]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_12 (Conv2D)                   │ (None, 126, 126, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_12 (MaxPooling2D)      │ (None, 63, 63, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_13 (Conv2D)                   │ (None, 61, 61, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_13 (MaxPooling2D)      │ (None, 30, 30, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_14 (Conv2D)                   │ (None, 28, 28, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_14 (MaxPooling2D)      │ (None, 14, 14, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_4 (Flatten)                  │ (None, 25088)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 512)                 │      12,845,568 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 10)                  │           5,130 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ time_distributed_6 (TimeDistributed) │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 38,831,840 (148.13 MB)

 Trainable params: 12,943,946 (49.38 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 25,887,894 (98.75 MB)

### Audio-video matcher

##### Extracting audio from the video

In [314]:
!pip install moviepy

In [319]:
from moviepy.editor import AudioFileClip

def extract_audio_from_video(video_path):
    video = VideoFileClip(video_path)
    audio = video.audio
    audio.write_audiofile(video_path.replace('.mp4', '.wav'))
    return video_path.replace('.mp4', '.wav')



In [317]:
!pip install librosa

In [318]:
import librosa

In [320]:
extract_audio_from_video(r"C:\Users\101ri\OneDrive\Desktop\deep fake detector\Notebook\train_sample_videos\aagfhgtpmv.mp4")

MoviePy - Writing audio in C:\Users\101ri\OneDrive\Desktop\deep fake detector\Notebook\train_sample_videos\aagfhgtpmv.wav


MoviePy - Done.


'C:\\Users\\101ri\\OneDrive\\Desktop\\deep fake detector\\Notebook\\train_sample_videos\\aagfhgtpmv.wav'

### Model- Training

In [323]:
from tensorflow.keras.callbacks import ModelCheckpoint

## final model cnn-lstm
checkpoint = ModelCheckpoint('best_model.keras', monitor='val_accuracy', save_best_only=True)
cnn_lstm_model.fit(X_train, y_train, validation_split=0.2, epochs=10, callbacks=[checkpoint])



Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 20s 20s/step - accuracy: 1.0000 - loss: 0.0141 - val_accuracy: 1.0000 - val_loss: 0.0130
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 13s 13s/step - accuracy: 1.0000 - loss: 0.0130 - val_accuracy: 1.0000 - val_loss: 0.0119
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 26s 26s/step - accuracy: 1.0000 - loss: 0.0119 - val_accuracy: 1.0000 - val_loss: 0.0111
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 20s 20s/step - accuracy: 1.0000 - loss: 0.0111 - val_accuracy: 1.0000 - val_loss: 0.0103
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 23s 23s/step - accuracy: 1.0000 - loss: 0.0103 - val_accuracy: 1.0000 - val_loss: 0.0096
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 22s 22s/step - accuracy: 1.0000 - loss: 0.0096 - val_accuracy: 1.0000 - val_loss: 0.0090
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 29s 29s/step - accuracy: 1.0000 - loss: 0.0090 - val_accuracy: 1.0000 - val_loss: 0.0084
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 18s 18s/step - accuracy: 1.0000 - loss: 0.0084 - val_accuracy: 1.0000 - val_loss: 0.0079


In [325]:
## from the above we observe that lstm-cnn is best as it has good accuracy 
cnn_lstm_model.save('cnn_lstm_model.h5')

In [327]:
from tensorflow.keras.models import load_model

model = load_model('cnn_lstm_model.h5')


In [328]:
import cv2
import numpy as np

def preprocess_video(video_path, frame_size=(128, 128), num_frames=30):
    # Open the video file
    cap = cv2.VideoCapture(video_path)
    
    frames = []
    while len(frames) < num_frames:
        ret, frame = cap.read()
        if not ret:
            break
        # Resize frame
        frame = cv2.resize(frame, frame_size)
        # Normalize pixel values
        frame = frame / 255.0
        frames.append(frame)
    
    # Pad or truncate frames to the required number of frames
    if len(frames) < num_frames:
        frames += [np.zeros(frame_size + (3,))] * (num_frames - len(frames))
    else:
        frames = frames[:num_frames]
    
    cap.release()
    return np.array(frames)


In [331]:
from tensorflow.keras.models import load_model
import cv2
import numpy as np

# Load the model
model = load_model('cnn_lstm_model.h5')

def preprocess_video(video_path, frame_size=(128, 128), num_frames=30):
    cap = cv2.VideoCapture(video_path)
    frames = []
    while len(frames) < num_frames:
        ret, frame = cap.read()
        if not ret:
            break
        frame = cv2.resize(frame, frame_size)
        frame = frame / 255.0
        frames.append(frame)
    if len(frames) < num_frames:
        frames += [np.zeros(frame_size + (3,))] * (num_frames - len(frames))
    else:
        frames = frames[:num_frames]
    cap.release()
    return np.array(frames)

def check_video(video_path):
    video_data = preprocess_video(video_path)
    predictions = model.predict(np.expand_dims(video_data, axis=0))  # Add batch dimension
    print(f"Model prediction: {predictions}")

    # Assuming the output is a probability, you can set a threshold
    threshold = 0.5
    if predictions[0][0] > threshold:
        return "It's a deepfake"
    else:
        return "It's not a deepfake"



In [335]:
# Example usage
result = check_video(r"C:\Users\101ri\OneDrive\Desktop\deep fake detector\Notebook\deepfakevideo.mp4")
print(result)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step
Model prediction: [[0.0069974]]
It's not a deepfake


In [357]:
print(f'X_train shape: {X_train.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_test shape: {y_test.shape}')


X_train shape: (0, 30, 128, 128, 3)
y_train shape: (327,)
X_test shape: (82, 128, 128, 3)
y_test shape: (82,)


In [352]:
# Assuming X_train is your data with shape (num_samples, 128, 128, 3)
num_samples = X_train.shape[0]
num_sequences = num_samples // 30  # Number of sequences you can form

# Reshape data into sequences
X_train = X_train[:num_sequences * 30].reshape(num_sequences, 30, 128, 128, 3)


In [354]:
def create_cnn_lstm_model():
    model = Sequential([
        TimeDistributed(Conv2D(32, (3, 3), activation='relu'), input_shape=(30, 128, 128, 3)),
        TimeDistributed(MaxPooling2D((2, 2))),
        TimeDistributed(Flatten()),
        LSTM(64, return_sequences=False),
        
        Dense(64, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer
                  =Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])
    return model

In [355]:
# Training CNN-LSTM
cnn_lstm_model = create_cnn_lstm_model()
history_cnn_lstm = cnn_lstm_model.fit(X_train, y_train, epochs=20, batch_size=8, validation_split=0.2)
loss_cnn_lstm, accuracy_cnn_lstm = cnn_lstm_model.evaluate(X_test, y_test)
print(f'CNN-LSTM Model Test Accuracy: {accuracy_cnn_lstm:.4f}')

ValueError: Training data contains 0 samples, which is not sufficient to split it into a validation and training set as specified by `validation_split=0.2`. Either provide more data, or a different value for the `validation_split` argument.

In [341]:
# Train and save CNN-LSTM model
cnn_lstm_model = create_cnn_lstm_model2()
cnn_lstm_history = cnn_lstm_model.fit(X_train, y_train, epochs=20, batch_size=8, validation_split=0.2)
cnn_lstm_loss, cnn_lstm_accuracy = cnn_lstm_model.evaluate(X_test, y_test)
print(f'CNN-LSTM Model Test Accuracy: {cnn_lstm_accuracy:.4f}')
cnn_lstm_model.save('cnn_lstm_model2.h5')


ValueError: Training data contains 0 samples, which is not sufficient to split it into a validation and training set as specified by `validation_split=0.2`. Either provide more data, or a different value for the `validation_split` argument.

In [356]:
import matplotlib.pyplot as plt

def visualize_predictions(model, X_test, y_test, num_samples=5):
    y_pred = model.predict(X_test[:num_samples])
    y_pred_classes = (y_pred > 0.5).astype("int32")
    
    for i in range(num_samples):
        plt.figure(figsize=(10, 5))
        plt.subplot(1, 2, 1)
        plt.imshow(X_test[i][0])  # Display first frame of the video
        plt.title(f"Label: {y_test[i]}, Pred: {y_pred_classes[i][0]}")
        plt.axis('off')
        plt.show()

visualize_predictions(cnn_lstm_model, X_test, y_test)


ValueError: Exception encountered when calling Sequential.call().

Invalid input shape for input Tensor("data:0", shape=(5, 128, 128, 3), dtype=float32). Expected shape (None, 30, 128, 128, 3), but input has incompatible shape (5, 128, 128, 3)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(5, 128, 128, 3), dtype=float32)
  • training=False
  • mask=None

In [ ]:
from tensorflow.keras.models import load_model
import cv2
import numpy as np

# Load the model
model = load_model('cnn_lstm_model2.h5')

def preprocess_video(video_path, frame_size=(128, 128), num_frames=30):
    cap = cv2.VideoCapture(video_path)
    frames = []
    while len(frames) < num_frames:
        ret, frame = cap.read()
        if not ret:
            break
        frame = cv2.resize(frame, frame_size)
        frame = frame / 255.0
        frames.append(frame)
    if len(frames) < num_frames:
        frames += [np.zeros(frame_size + (3,))] * (num_frames - len(frames))
    else:
        frames = frames[:num_frames]
    cap.release()
    return np.array(frames)

def check_video(video_path):
    video_data = preprocess_video(video_path)
    predictions = model.predict(np.expand_dims(video_data, axis=0))  # Add batch dimension
    print(f"Model prediction: {predictions}")

    # Assuming the output is a probability, you can set a threshold
    threshold = 0.5
    if predictions[0][0] > threshold:
        return "It's a deepfake"
    else:
        return "It's not a deepfake"



In [ ]:
# Example usage
result = check_video(r"C:\Users\101ri\OneDrive\Desktop\deep fake detector\Notebook\deepfakevideo.mp4")
print(result)
